[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self' fonts.gstatic.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://plantforfuture-0aad8652667a.herokuapp.com/api/:splat"
  status = 200
