[dev]
  targetPort = 8080

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://plantforfuture-0aad8652667a.herokuapp.com/:splat"
  status = 200
  force = true
